- name: Oscar
  image: /img/cats/cat1.jpg
- name: Misty
  image: /img/cats/cat2.jpg
- name: Smokey
  image: /img/cats/cat3.jpg
- name: Coco
  image: /img/cats/cat4.jpg
- name: Jasper
  image: /img/cats/cat5.jpg
- name: Molly
  image: /img/cats/cat6.jpg
- name: Trevor
  image: /img/cats/cat7.jpg
- name: Bella
  image: /img/cats/cat8.jpg
- name: Lucy
  image: /img/cats/cat9.jpg
